<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="../../css/normalize.css" type="text/css">
    <link rel="stylesheet" href="../../css/skeleton.css" type="text/css">
    <link rel="stylesheet" href="../../css/myown.css" type="text/css">
</head>
<body>
    <div class="container">
        <?php echo $content ?>
    </div>
</body>
</html>