<div>
    <p>
        <?php
        echo $post->getContent();?>
    </p>
    <div>
        <?php
        foreach ($comments as $comment)
        echo '<p>' . $comment->getContent() . '</p>'?>
    </div>
</div>

<div>
    <form method="post" action="<?= App::config('url') ?>/Index/newComment">

        <div class="form-group" id="comment_form">
            <label for="content">Share Your thoughts about the Topic: </label>
            <input id="content" name="content" type="text">
            <input id="post_id" name="post_id" type="hidden" value="<?= $post->getId(); ?>">
        </div>

        <button type="submit">Comment</button>
    </form>
</div>