<div>
    <p>
        <?php
        echo htmlspecialchars($post->getContent());?>
    </p>
    <?php if($post->getImage()):?>
        <p>
        <img class='images' src="<?php echo htmlspecialchars(App::config('url') . '/images/' . $post->getImage()); ?>" alt="image">
        </p><?php
    endif;?>
    <div>
        <h5>Comments: </h5>
        <?php
        foreach ($comments as $comment)
            echo '<p class="bordered">' . htmlspecialchars($comment->getContent()) . '</p>'?>
    </div>
</div>
<div>
    <form method="post" action="<?= App::config('url') ?>/Index/newComment">
        <div class="form-group">
            <label for="content">Share Your thoughts about the Topic: </label>
            <input id="content" name="content" type="text">
            <input id="post_id" name="post_id" type="hidden" value="<?= $post->getId(); ?>">
        </div>
        <button class="button button-primary" type="submit">Comment</button>
    </form>
    <hr />
</div>
<div>
    <form method="post" action="<?= App::config('url') ?>/Index/deletePost">
        <div class="form-group">
            <input id="id" name="id" type="hidden" value="<?= $post->getId(); ?>">
            <button class="button button-primary" type="submit">Delete Post</button>
        </div>
    </form>
</div>

